import { NgModule } from '@angular/core';
import { NativeScriptRouterModule } from 'nativescript-angular/router';
import { Routes } from '@angular/router';

import { AutoGeneratedComponent } from '@src/app/mobile-app/mobile-app.component';

export const routes: Routes = [
  {
      path: '',
      redirectTo: '/mobile-app',
      pathMatch: 'full',
  },
  {
      path: 'mobile-app',
      component: AutoGeneratedComponent,
  },
];

@NgModule({
  imports: [NativeScriptRouterModule.forRoot(routes)],
  exports: [NativeScriptRouterModule]
})
export class AppRoutingModule { }
