import { RouterModule, Routes, Router } from '@angular/router';
import { NgModule } from '@angular/core';

//component
import { EntriesComponent } from './entries/entries.component';
import {NewEntryComponent} from './new-entry/new-entry.component';
//import {DeleteEntryComponent} from './delete-entry/delete-entry.component';
import { AutoGeneratedComponent } from './mobile-app/mobile-app.component';
import { RegisterComponent } from './register/register.component';

//route
const routes:Routes = [
    {path: '', component:EntriesComponent},
    {path: 'entries', component:EntriesComponent},
    {path:'new-entry', component:NewEntryComponent},
    //{path:'delete-entry/:id', component:DeleteEntryComponent},
    {path: 'mobile-app', component:AutoGeneratedComponent},
    {path: 'register', component:RegisterComponent}
]

@NgModule({
        imports: [RouterModule.forRoot(routes)],
        exports: [RouterModule]
})

export class AppRouterModule{}