import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { AppComponent } from '@src/app/app.component';
import { AutoGeneratedComponent } from '@src/app/mobile-app/mobile-app.component';
import { EntriesComponent } from '@src/app/entries/entries.component';
import { FooterComponent } from '@src/app/footer/footer.component';
import { HeaderComponent } from '@src/app/header/header.component';

//services
import { EntryService } from '@src/app/services/entry.service';
import { AppRouterModule } from '@src/app/app-router.module';
import { HttpClientModule } from '@angular/common/http';
import { AuthService } from '@src/app/services/auth.service';

//material design
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { MatButtonModule, MatInputModule, MatCardModule, MatSelectModule, MatTableModule, MatToolbarModule, MatDialogModule, MatListModule } from '@angular/material';
//import { RegisterComponent } from '@src/app/register/register.component';

//forms
import {ReactiveFormsModule} from '@angular/forms';
import { RegisterComponent } from '@src/app/register/register.component';
import { NewEntryComponent } from '@src/app/new-entry/new-entry.component';
//import { LoginComponent } from './login/login.component';

@NgModule({
  declarations: [
    AppComponent,
    AutoGeneratedComponent,
    EntriesComponent,
    FooterComponent,
    HeaderComponent,
    RegisterComponent,
    NewEntryComponent
  ],
  imports: [
    BrowserModule,
    AppRouterModule,
    HttpClientModule,
    //material design
    BrowserAnimationsModule, MatButtonModule, MatInputModule, MatCardModule, MatSelectModule, MatTableModule, MatToolbarModule, MatDialogModule, MatListModule,ReactiveFormsModule
  ],
  providers: [EntryService, AuthService],
  bootstrap: [AppComponent]
})
export class AppModule { }
