import { NgModule, NO_ERRORS_SCHEMA } from '@angular/core';
import { NativeScriptModule } from 'nativescript-angular/nativescript.module';

import { AppRoutingModule } from '@src/app/app-routing.module.tns';
import { AppComponent } from '@src/app/app.component';
import { AutoGeneratedComponent } from '@src/app/mobile-app/mobile-app.component';
import { EntriesComponent } from '@src/app/entries/entries.component';
import { FooterComponent } from '@src/app/footer/footer.component';
import { HeaderComponent } from '@src/app/header/header.component';
import { RegisterComponent } from '@src/app/register/register.component';
import { NewEntryComponent } from '@src/app/new-entry/new-entry.component';


// Uncomment and add to NgModule imports if you need to use two-way binding
// import { NativeScriptFormsModule } from 'nativescript-angular/forms';

// Uncomment and add to NgModule imports  if you need to use the HTTP wrapper
// import { NativeScriptHttpClientModule } from 'nativescript-angular/http-client';

@NgModule({
  declarations: [
    AppComponent,
    AutoGeneratedComponent,
    EntriesComponent,
    FooterComponent,
    HeaderComponent,
    RegisterComponent,
    NewEntryComponent
  ],
  imports: [
    NativeScriptModule,
    AppRoutingModule,
  ],
  providers: [],
  bootstrap: [AppComponent],
  schemas: [NO_ERRORS_SCHEMA]
})
/*
Pass your application module to the bootstrapModule function located in main.ts to start your app
*/
export class AppModule { }
