import { Component, OnInit } from '@angular/core';
import { ItemEventData, ListView } from "tns-core-modules/ui/list-view";
import { ChangeDetectionStrategy } from "@angular/core";

import { EntryService } from '../services/entry.service';
import { DataSource } from '@angular/cdk/table';
import { MatTableDataSource } from '@angular/material/table';
import { EntryElement } from '../interfaces/EntryElement';

class Country {
  constructor(public name: string) { }
}

let europianCountries = ["Austria", "Belgium", "Bulgaria", "Croatia", "Cyprus", "Czech Republic",
    "Denmark", "Estonia", "Finland", "France", "Germany", "Greece", "Hungary", "Ireland", "Italy",
    "Latvia", "Lithuania", "Luxembourg", "Malta", "Netherlands", "Poland", "Portugal", "Romania", "Slovakia",
    "Slovenia", "Spain", "Sweden", "United Kingdom"];

@Component({
  moduleId: module.id,
  selector: 'app-auto-generated',
  templateUrl: './mobile-app.component.html',
  styleUrls: ['./mobile-app.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class AutoGeneratedComponent implements OnInit {
  public countries: Array<Country>;
  public displayedColumns: string[] = ['Id', 'Description', 'IsExpense', 'Value']
  public dataSource;


  constructor(private service:EntryService) {//private service:EntryService
    this.countries = [];
    for (let i = 0; i < europianCountries.length; i++) {
      this.countries.push(new Country(europianCountries[i]));
    }
   }

  ngOnInit() {
    this.service.getAll().subscribe((data) => {
      //console.log('Result - ', data);
      this.dataSource = new MatTableDataSource<EntryElement>(data as EntryElement[])
    })

  }
  // public Student = ["Peter", "Bob", "Vasja"];
}
